### ISSUE TITLE
Address Security Alerts -- OAI Gem

### ISSUE THREAD

**Issue by dl-maura** [harvard-lts/spotlight-oaipmh-resources#31]

**Comment by dl-maura** [comment]
This is in progress, PR here:

https://github.com/harvard-lts/spotlight-oaipmh-resources/pull/42

@phil-plencner-hl @bkiahstroud tagged for testing but seemed to work on my local

**Comment by VanessaVenti** [comment]
Done for now. This is a reoccuring issue.
