### ISSUE TITLE
Add ming to solr id section in harvester

### ISSUE THREAD

**Issue by dl-maura** [harvard-lts/spotlight-oaipmh-resources#55]
Ming alias doesn't seem to be working because it is using the wrong id field, needs a code change in oai gem

**Comment by enriquediaz** [comment]
I think this work has been done, because I see the Ming collection in production: https://curiosity.lib.harvard.edu/index-ming-dynasty-chinese-paintings

@VanessaVenti can you confirm and close if so?

**Comment by dl-maura** [comment]
@enriquediaz this is actually a code change in the harvester to allow the alias of 'ming' to work

**Comment by dl-maura** [comment]
PR for oai gem:
https://github.com/harvard-lts/spotlight-oaipmh-resources/pull/57

Then we will need to make a new release and a PR to curiosity proper

**Comment by dl-maura** [comment]
This is also in QA for @VanessaVenti

**Comment by VanessaVenti** [comment]
Looks good on QA!
